---
abstract: 'ZofCMS plugin to handle file uploads'
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-FileUpload
provides:
  App::ZofCMS::Plugin::FileUpload:
    file: lib/App/ZofCMS/Plugin/FileUpload.pm
    version: 0.0114
requires:
  App::ZofCMS: 0.0104
  File::Spec::Functions: 3.2701
resources:
  license: http://dev.perl.org/licenses/
version: 0.0114
